version: "3"
services:
  selenium-hub: 
    image: selenium/hub:4.16
    container_name: selenium-hub
    ports:
    - 4444:4444
  chrome:
    image: selenium/node-chrome:4.16
    shm_size: 2gb
    depends_on:
    - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=3
  firefox:
    image: selenium/node-firefox:4.16
    shm_size: 2gb
    depends_on:
    - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=3
  login_suite:
    image: guttekkk/selenium-training
    depends_on:
    - chrome
    - firefox
    environment:
      - automation_password=secret_sauce
      - grid_address=selenium-hub
      - TEST_GROUP=login
  cart_items_suite:
    image: guttekkk/selenium-training
    depends_on:
    - chrome
    - firefox
    environment:
      - automation_password=secret_sauce
      - grid_address=selenium-hub
      - TEST_GROUP=cart_items