version: "3"
services:
  test_suite:
    image: guttekkk/selenium-training
    environment:
      - automation_password=secret_sauce
      - grid_address=selenium-hub
      - TEST_GROUP
      - BROWSER
    volumes:
      - ./results/test_suite:/app/test_results